apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-app
  labels:
    app: zomato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: zomato-container
          image: rutikesh1907/zomato:latest   # ðŸ‘ˆ your Docker image
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
